# This workflow will test the build system, then build the extension and upload an artifact
name: Test build system and upload extension

on:
  push:
    # only trigger on branches, not on tags
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Packages
      run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y make gettext gnome-shell
    #- uses: awalsh128/cache-apt-pkgs-action@v1
      #with:
        #packages: make gettext gnome-shell gnome-shell-extension-prefs gnome-shell-extensions
        #version: 1.0

    - name: Test extension builds from scratch
      run: |
        make build

    - name: linter
      uses: reviewdog/action-eslint@2fee6dd72a5419ff4113f694e2068d2a03bb35dd # v1.33.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
        eslint_flags: "tailscale-gnome-qs@tailscale-qs.github.io/"
        fail_level: warning
