name: reviewdog eslint pr
on: [pull_request, workflow_dispatch]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-eslint@v1.34.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: "tailscale-gnome-qs@tailscale-qs.github.io/"
          fail_level: warning
