name: Reviewdog ESLint PR
on: [pull_request]
jobs:
  eslint:
    name: runner-eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout pr
        uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - uses: reviewdog/action-eslint@v1.34.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: "tailscale-gnome-qs@tailscale-qs.github.io/"
          fail_level: warning
